on:
  workflow_call:
    inputs:
      disableCodeQL:
        required: false
        type: boolean
        default: false
      disablePublish:
        required: false
        type: boolean
        default: false
      dotnet-logging:
        required: false
        type: string
        default: minimal
      dotnet-testfilter:
        required: false
        type: string
        default: ''
      dotnet-version:
        required: false
        type: string
        default: 7.x
      dotnet-quality:
        required: false
        type: string
        default: ga
      enableSonarQube:
        required: false
        type: boolean
        default: false
      runs-on-build:
        required: false
        type: string
        default: 'ubuntu-latest'
      runs-on-tests:
        required: false
        type: string
        default: 'ubuntu-latest'
      solution:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Validate Code formatting
    uses: ./.github/workflows/step-dotnet-format.yml
    with:
      dotnet-logging: ${{ inputs.dotnet-logging || 'minimal' }}
      dotnet-version: ${{ inputs.dotnet-version || '7.x' }}
      dotnet-quality: ${{ inputs.dotnet-quality || 'ga' }}
      solution: ${{ inputs.solution }}

  pretest:
    name: Prepare Test Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - name: Generate Matrix
        id: generate
        run: |
          echo "matrix=${{ format('[{0}]', inputs.dotnet-testfilter) }}" >> $GITHUB_OUTPUT

  tests:
    name: Tests .NET
    uses: ./.github/workflows/step-dotnet-tests.yml
    needs:
      - format
      - pretest
    strategy:
      matrix:
        testfilter: ${{ fromJson(needs.pretest.outputs.matrix) }}
    with:
      enableSonarQube: ${{ inputs.enableSonarQube || false }}
      dotnet-logging: ${{ inputs.dotnet-logging || 'minimal' }}
      dotnet-testfilter: ${{ matrix.testfilter || '' }}
      dotnet-version: ${{ inputs.dotnet-version || '7.x' }}
      dotnet-quality: ${{ inputs.dotnet-quality || 'ga' }}
      runs-on: ${{ inputs.runs-on-tests || 'ubuntu-latest' }}
      solution: ${{ inputs.solution }}
    secrets: inherit

  codeql:
    name: CodeQL .NET
    if: ${{ inputs.disableCodeQL == false }}
    uses: ./.github/workflows/step-dotnet-codeql.yml
    needs:
      - format
    with:
      dotnet-logging: ${{ inputs.dotnet-logging || 'minimal' }}
      dotnet-version: ${{ inputs.dotnet-version || '7.x' }}
      dotnet-quality: ${{ inputs.dotnet-quality || 'ga' }}
      solution: ${{ inputs.solution }}

  build:
    name: Build .NET
    uses: ./.github/workflows/step-dotnet-build.yml
    needs:
      - tests
    with:
      dotnet-logging: ${{ inputs.dotnet-logging || 'minimal' }}
      dotnet-version: ${{ inputs.dotnet-version || '7.x' }}
      dotnet-quality: ${{ inputs.dotnet-quality || 'ga' }}
      runs-on: ${{ inputs.runs-on-build || 'ubuntu-latest' }}
      solution: ${{ inputs.solution }}
    secrets: inherit

  nuget:
    name: Publish NuGet.org
    if: ${{ inputs.disablePublish == false }}
    uses: ./.github/workflows/step-dotnet-publish-nuget.yml
    needs:
      - build
      - codeql
    secrets: inherit



