on:
  workflow_call:
    inputs:
      disableCodeQL:
        required: false
        type: boolean
        default: false
      disablePublish:
        required: false
        type: boolean
        default: false
      dotnet-logging:
        required: false
        type: string
        default: minimal
      dotnet-testfilter:
        required: false
        type: string
        default: ''
      dotnet-version:
        required: false
        type: string
        default: 7.x
      dotnet-quality:
        required: false
        type: string
        default: ga
      enableSonarQube:
        required: false
        type: boolean
        default: false
      runs-on-build:
        required: false
        type: string
        default: 'ubuntu-latest'
      runs-on-tests:
        required: false
        type: string
        default: 'ubuntu-latest'
      solution:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow_ref }}@${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    name: Determine solution version
    uses: ./.github/workflows/step-dotnet-version.yml
    with:
      dotnet-version: ${{ inputs.dotnet-version || '7.x' }}
      dotnet-quality: ${{ inputs.dotnet-quality || 'ga' }}

  format:
    name: Validate Code formatting
    uses: ./.github/workflows/step-dotnet-format.yml
    with:
      dotnet-logging: ${{ inputs.dotnet-logging || 'minimal' }}
      dotnet-version: ${{ inputs.dotnet-version || '7.x' }}
      dotnet-quality: ${{ inputs.dotnet-quality || 'ga' }}
      solution: ${{ inputs.solution }}

  codeql:
    name: CodeQL .NET
    if: ${{ inputs.disableCodeQL == false }}
    uses: ./.github/workflows/step-dotnet-codeql.yml
    with:
      dotnet-logging: ${{ inputs.dotnet-logging || 'minimal' }}
      dotnet-version: ${{ inputs.dotnet-version || '7.x' }}
      dotnet-quality: ${{ inputs.dotnet-quality || 'ga' }}
      solution: ${{ inputs.solution }}

  tests:
    name: Tests .NET
    needs:
      - version
    uses: ./.github/workflows/step-dotnet-tests.yml
    with:
      enableSonarQube: ${{ inputs.enableSonarQube || false }}
      dotnet-logging: ${{ inputs.dotnet-logging || 'minimal' }}
      dotnet-testfilter: ${{ inputs.dotnet-testfilter }}
      dotnet-version: ${{ inputs.dotnet-version || '7.x' }}
      dotnet-quality: ${{ inputs.dotnet-quality || 'ga' }}
      runs-on: ${{ inputs.runs-on-tests || 'ubuntu-latest' }}
      solution: ${{ inputs.solution }}
      solution-version: ${{ needs.version.outputs.solution-version }}
    secrets: inherit

  build:
    name: Build .NET
    uses: ./.github/workflows/step-dotnet-build.yml
    needs:
      - tests
    with:
      dotnet-logging: ${{ inputs.dotnet-logging || 'minimal' }}
      dotnet-version: ${{ inputs.dotnet-version || '7.x' }}
      dotnet-quality: ${{ inputs.dotnet-quality || 'ga' }}
      runs-on: ${{ inputs.runs-on-build || 'ubuntu-latest' }}
      solution: ${{ inputs.solution }}
    secrets: inherit

  nuget:
    name: Publish NuGet.org
    if: ${{ inputs.disablePublish == false && github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/step-dotnet-publish-nuget.yml
    needs:
      - build
      - codeql
    secrets: inherit

  release:
    name: Create GitHub Draft Release
    if: ${{ inputs.disablePublish == false && github.actor != 'dependabot[bot]' }}
    needs:
      - version
      - build
      - codeql
    uses: ./.github/workflows/step-dotnet-draft-release.yml
    with:
      runs-on: ${{ inputs.runs-on-tests || 'ubuntu-latest' }}
      solution-version: ${{ needs.version.outputs.solution-version }}

