on:
  workflow_call:
    inputs:
      disableCodeFormat:
        required: false
        type: boolean
        default: false
      disableCodeQL:
        required: false
        type: boolean
        default: false
      disableCoverageUpload:
        required: false
        type: boolean
        default: false
      disablePublish:
        required: false
        type: boolean
        default: false
      dotnet-logging:
        required: false
        type: string
        default: quiet
      dotnet-testfilter:
        required: false
        type: string
        default: ''
      dotnet-version:
        required: false
        type: string
        default: 8.x
      dotnet-quality:
        required: false
        type: string
        default: ga
      enableSonarQube:
        required: false
        type: boolean
        default: false
      runs-on-build:
        required: false
        type: string
        default: 'ubuntu-latest'
      runs-on-tests:
        required: false
        type: string
        default: 'ubuntu-latest'
      solution:
        required: true
        type: string
    secrets:
      FETCH_TOKEN:
        required: false

concurrency:
  group: ${{ github.workflow_ref }}@${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: true

jobs:
  version:
    name: Version
    uses: ./.github/workflows/step-dotnet-version.yml
    with:
      dotnet-version: ${{ inputs.dotnet-version || '8.x' }}
      dotnet-quality: ${{ inputs.dotnet-quality || 'ga' }}
    secrets: inherit

  format:
    name: Format
    if: ${{ inputs.disableCodeFormat == false }}
    uses: ./.github/workflows/step-dotnet-format.yml
    with:
      dotnet-logging: ${{ inputs.dotnet-logging || 'quiet' }}
      dotnet-version: ${{ inputs.dotnet-version || '8.x' }}
      dotnet-quality: ${{ inputs.dotnet-quality || 'ga' }}
      runs-on: ${{ inputs.runs-on-build || 'ubuntu-latest' }}
      solution: ${{ inputs.solution }}
    secrets: inherit

  codeql:
    name: CodeQL
    if: ${{ inputs.disableCodeQL == false }}
    uses: ./.github/workflows/step-dotnet-codeql.yml
    with:
      dotnet-logging: ${{ inputs.dotnet-logging || 'quiet' }}
      dotnet-version: ${{ inputs.dotnet-version || '8.x' }}
      dotnet-quality: ${{ inputs.dotnet-quality || 'ga' }}
      runs-on: ${{ inputs.runs-on-build || 'ubuntu-latest' }}
      solution: ${{ inputs.solution }}
    secrets: inherit

  tests:
    name: Tests
    needs:
      - version
    uses: ./.github/workflows/step-dotnet-tests.yml
    with:
      enableSonarQube: ${{ inputs.enableSonarQube || false }}
      disableCoverageUpload: ${{ inputs.disableCoverageUpload || false }}
      dotnet-logging: ${{ inputs.dotnet-logging || 'quiet' }}
      dotnet-testfilter: ${{ inputs.dotnet-testfilter }}
      dotnet-version: ${{ inputs.dotnet-version || '8.x' }}
      dotnet-quality: ${{ inputs.dotnet-quality || 'ga' }}
      runs-on: ${{ inputs.runs-on-tests || inputs.runs-on-build || 'ubuntu-latest' }}
      solution: ${{ inputs.solution }}
      solution-version: ${{ needs.version.outputs.solution-version }}
    secrets: inherit

  build:
    name: Build
    uses: ./.github/workflows/step-dotnet-build.yml
    needs:
      - tests
      - format
    with:
      dotnet-logging: ${{ inputs.dotnet-logging || 'quiet' }}
      dotnet-version: ${{ inputs.dotnet-version || '8.x' }}
      dotnet-quality: ${{ inputs.dotnet-quality || 'ga' }}
      runs-on: ${{ inputs.runs-on-build || 'ubuntu-latest' }}
      solution: ${{ inputs.solution }}
    secrets: inherit

  dependabot-merge:
    name: Dependabot Merge
    if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
    uses: ./.github/workflows/step-dependabot-merge.yml
    needs:
      - build
    secrets: inherit

  publish-nuget:
    name: Publish NuGet
    if: ${{ inputs.disablePublish == false && github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/step-dotnet-publish-nuget.yml
    needs:
      - build
      - codeql
    secrets: inherit

  release:
    name: Release
    if: ${{ inputs.disablePublish == false && github.actor != 'dependabot[bot]' }}
    needs:
      - version
      - build
      - codeql
      - publish-nuget
    uses: ./.github/workflows/step-dotnet-draft-release.yml
    with:
      runs-on: ${{ inputs.runs-on-tests || 'ubuntu-latest' }}
      solution-version: ${{ needs.version.outputs.solution-version }}
    secrets: inherit
