name: Create pipelines release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  version:
    name: Version
    uses: ./.github/workflows/step-dotnet-version.yml
    with:
      dotnet-version: '8.x'
      dotnet-quality: 'ga'

  release:
    name: Release
    needs:
      - version
    uses: ./.github/workflows/step-dotnet-draft-release.yml
    with:
      runs-on: 'ubuntu-latest'
      solution-version: ${{ needs.version.outputs.solution-version }}
