name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  all:
    name: Build & Tests
    uses: dailydevops/pipelines/.github/workflows/cicd-dotnet.yml@0.12.47
    with:
      enableCleanUpDockerDocker: true
      enableSonarQube: false
      dotnet-version: ${{ vars.NE_DOTNET_TARGETFRAMEWORKS }}
      dotnet-quality: ${{ vars.NE_DOTNET_QUALITY }}
      solution: ./TestProjects/HealthChecks.sln
    secrets: inherit
