on:
  workflow_call:
    inputs:
      cache-restore-key:
        required: true
        type: string
      dotnet-logging:
        required: false
        type: string
        default: minimal
      dotnet-version:
        required: false
        type: string
        default: 7.x
      solution:
        required: true
        type: string

env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Load NuGet Cache
      uses: actions/cache@v3
      id: nuget-cache
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ inputs.cache-restore-key }}-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ inputs.cache-restore-key }}

    - name: Restore dependencies
      if: steps.nuget-cache.outputs.cache-hit != 'true'
      run: dotnet restore ${{ inputs.solution }}

    - name: Build
      run: dotnet build ${{ inputs.solution }} -c Release --no-restore

    - name: Upload NuGet packages
      uses: actions/upload-artifact@v3
      with:
        name: release-packages
        path: |
          **/*.nupkg
          **/*.snupkg
