on:
  workflow_call:
    inputs:
      dotnet-logging:
        required: false
        type: string
        default: minimal
      dotnet-version:
        required: false
        type: string
        default: 7.x
      dotnet-quality:
        required: false
        type: string
        default: ga
      solution:
        required: true
        type: string

defaults:
  run:
    shell: pwsh

jobs:
  format:
    name: Validate Code Formatting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        dotnet-quality: ${{ inputs.dotnet-quality }}

    - name: Install `dotnet-format` tool
      run: dotnet tool install -g dotnet-format

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.solution }} -v ${{ inputs.dotnet-logging }}

    - name: Execute `dotnet-format`
      run: dotnet format ${{ inputs.solution }} --verify-no-changes --verbosity ${{ inputs.dotnet-logging }}
