on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      solution-version:
        required: true
        type: string

env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_NOLOGO: true

jobs:
  draft-release:
    name: Draft Release
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Release Drafter
      uses: release-drafter/release-drafter@v5.25.0
      with:
        version: ${{ inputs.solution-version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
