on:
  workflow_call:
    inputs:
      dotnet-logging:
        required: false
        type: string
        default: minimal
      dotnet-testfilter:
        required: false
        type: string
        default: ''
      dotnet-version:
        required: false
        type: string
        default: 7.x
      dotnet-quality:
        required: false
        type: string
        default: ga
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      solution:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: false

env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_NOLOGO: true

jobs:
  testing:
    name: Testing
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        dotnet-quality: ${{ inputs.dotnet-quality }}
        cache: true

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.solution }} -v ${{ inputs.dotnet-logging }}

    - name: Test
      if: inputs.dotnet-testfilter == ''
      run: dotnet test ${{ inputs.solution }} -c Release -v ${{ inputs.dotnet-logging }} --no-restore --collect:"XPlat Code Coverage"

    - name: Test
      if: inputs.dotnet-testfilter != ''
      run: dotnet test ${{ inputs.solution }} -c Release -v ${{ inputs.dotnet-logging }} --no-restore --collect:"XPlat Code Coverage" --filter "TestCategory=${{ inputs.dotnet-testfilter }}"

    - name: Update codecov
      uses: codecov/codecov-action@v3
      env:
        codecov_token: ${{ secrets.CODECOV_TOKEN }}
      if: ${{ env.codecov_token != '' }}
      with:
        token: ${{ env.codecov_token }}
        fail_ci_if_error: true
