on:
  workflow_call:
    secrets:
      FETCH_TOKEN:
        required: false

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.FETCH_TOKEN || github.token }}

      - uses: actions/setup-node@v4.0.4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Run the commitlint action, considering its own dependencies and yours as well 🚀
      # `github.workspace` is the path to your repository.
      - uses: wagoid/commitlint-github-action@v6.1.2
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules